spring:
  main:
    banner-mode: "off"
  application:
    name: blank-resource-server
server:
    port: 8080
    
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: 3_2olch6wm3v6sso4ssswcsk0wocgwk0ckscowo0k4c88w0scwc8
      clientSecret: 3u3fumzdldycos8swg48so40skg0kkg0co04www04w04kgcgc0
      accessTokenUri: http://local.logincultura/oauth/v2/token
      userAuthorizationUri: http://local.logincultura/oauth/v2/auth
      clientAuthenticationScheme: form
    resource:
      userInfoUri: http://local.logincultura/api/v1/person